refresh:
  name: Refresh EPG
  description: >
    Force refresh of the TVHeadend EPG data.
    If entry_id is provided, only that config entry is refreshed.
  fields:
    entry_id:
      name: Config Entry ID
      description: Config entry ID to refresh
      example: "01KE7WVZQ05ACSGCXBAWE6ZMDE"
      selector:
        text:
